#第一次讀入CSV
#110學年度學生實習情形-以「系(所)」統計
#https://udb.moe.edu.tw/udata/DetailReportList/%E5%AD%B8%E7%94%9F%E9%A1%9E/SirdInternshipSituation/Index

In [2]:
import pandas as pd
df = pd.read_csv('W02_test.csv')
df.head()

,學年度,設立別,學校類別,學校統計處代碼,學校名稱,系所代碼,系所名稱,學制班別,寒假實習-人次-男,寒假實習-人次-女,...,暑期實習-總時數,全學期/單一學期-人次-男,全學期/單一學期-人次-女,全學期/單一學期-總時數,學期期間實習-人次-男,學期期間實習-人次-女,學期期間實習-總時數,全學年實習-人數-男,全學年實習-人數-女,全學年實習-總時數
0,110,公立,一般大學,0001,國立政治大學,03131032,心理學系,碩士班(日間),0,0,...,0.0,0,3,2160.0,4,19,3312.0,3,8,15840.0
1,110,公立,一般大學,0001,國立政治大學,03131032,心理學系,學士班(日間),0,0,...,2560.0,0,0,0.0,0,0,0.0,0,0,0.0
2,110,公立,一般大學,0001,國立政治大學,03214093,全球傳播與創新科技碩士學位學程,碩士班(日間),0,0,...,1056.0,0,0,0.0,0,0,0.0,0,0,0.0
3,110,公立,一般大學,0001,國立政治大學,04212073,法律學系,碩士班(日間),0,0,...,0.0,3,5,144.0,0,0,0.0,0,0,0.0
4,110,公立,一般大學,0001,國立政治大學,04212073,法律學系,學士班(日間),0,0,...,0.0,0,0,0.0,7,15,396.0,0,0,0.0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2870 entries, 0 to 2869
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   學年度            2870 non-null   int64
 1   設立別            2870 non-null   object
 2   學校類別           2870 non-null   object
 3   學校統計處代碼        2870 non-null   object
 4   學校名稱           2870 non-null   object
 5   系所代碼           2870 non-null   object
 6   系所名稱           2870 non-null   object
 7   學制班別           2870 non-null   object
 8   寒假實習-人次-男      2870 non-null   int64
 9   寒假實習-人次-女      2870 non-null   int64
 10  寒假實習-總時數       2870 non-null   float64
 11  暑期實習-人次-男      2870 non-null   int64
 12  暑期實習-人次-女      2870 non-null   int64
 13  暑期實習-總時數       2870 non-null   float64
 14  全學期/單一學期-人次-男  2870 non-null   int64
 15  全學期/單一學期-人次-女  2870 non-null   int64
 16  全學期/單一學期-總時數   2870 non-null   float64
 17  學期期間實習-人次-男    2870 non-null   int64
 18  學期期間實習-人次-女    2870 non-null   int64
 19  學期期間實習-總時數     2870 non-null   float64
 20  全學年實習-人數-男     2870 non-null   int64
 21  全學年實習-人數-女     2870 non-null   int64
 22  全學年實習-總時數      2870 non-null   float64
dtypes: float64(5), int64(11), object(7)
memory usage: 515.8+ KB

In [20]:
df['寒假實習-人次'] = df['暑期實習-人次-男'] + df['寒假實習-人次-女']
df['暑期實習-人次'] = df['暑期實習-人次-男'] + df['暑期實習-人次-女']
df['學期期間實習-人次'] = df['學期期間實習-人次-男'] + df['學期期間實習-人次-女']
df['全學年實習-人數'] = df['全學年實習-人數-男'] + df['全學年實習-人數-女']
temp = df[['學年度','學校名稱', '系所名稱', '寒假實習-人次', '寒假實習-總時數', '暑期實習-人次', '暑期實習-總時數', '全學期/單一學期-總時數', '學期期間實習-人次', '學期期間實習-總時數', '全學年實習-人數', '全學年實習-總時數']]
temp

,學年度,學校名稱,系所名稱,寒假實習-人次,寒假實習-總時數,暑期實習-人次,暑期實習-總時數,全學期/單一學期-總時數,學期期間實習-人次,學期期間實習-總時數,全學年實習-人數,全學年實習-總時數
0,110,國立政治大學,心理學系,0,0.0,0,0.0,2160.0,23,3312.0,11,15840.0
1,110,國立政治大學,心理學系,2,0.0,16,2560.0,0.0,0,0.0,0,0.0
2,110,國立政治大學,全球傳播與創新科技碩士學位學程,0,0.0,3,1056.0,0.0,0,0.0,0,0.0
3,110,國立政治大學,法律學系,0,0.0,0,0.0,144.0,0,0.0,0,0.0
4,110,國立政治大學,法律學系,0,0.0,0,0.0,0.0,22,396.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2865,110,臺北市立大學,都會產業經營與行銷學系,0,0.0,0,0.0,2400.0,0,0.0,0,0.0
2866,110,臺北市立大學,陸上運動學系,0,0.0,0,0.0,0.0,208,1764.0,0,0.0
2867,110,臺北市立大學,視覺藝術學系,0,0.0,0,0.0,700.0,0,0.0,0,0.0
2868,110,臺北市立大學,衛生福利學系,25,7680.0,0,0.0,0.0,0,0.0,0,0.0
2869,110,臺北市立大學,學習與媒材設計學系,6,0.0,40,6464.0,0.0,0,0.0,0,0.0

In [21]:
df['學校名稱'].value_counts()

國立臺灣大學            78
國立高雄科技大學          66
輔仁大學              64
逢甲大學              49
義守大學              44
                  ..
華梵大學               2
大華學校財團法人敏實科技大學     2
國立臺北藝術大學           2
臺北基督學院             1
台灣基督長老教會南神神學院      1
Name: 學校名稱, Length: 149, dtype: int64